version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: shadmansakib
      MINIO_ROOT_PASSWORD: shadmansakib
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
    command: server /data

  app:
    build: .
    container_name: minio-client-app
    environment:
      MINIO_ENDPOINT: minio
      MINIO_ACCESS_KEY: dinosorusonthefiled
      MINIO_SECRET_KEY: dinosorusonthefiled
      MINIO_BUCKET: denso
    depends_on:
      - minio
    ports:
      - "8080:8080"

volumes:
  minio-data: